#!/bin/sh

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#=======================================

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#=======================================

#BSPWM configuration
bspc config border_width 2;
bspc config window_gap 6;
bspc config single_monocle false;
bspc config split_ratio 0.52;
bspc config borderless_monocle true
bspc config gapless_monocle false 
bspc config focus_follows_pointer true;
bspc config pointer_modifier mod4;
bspc config pointer_action1 move;
bspc config pointer_action1 move;
bspc config pointer_action3 resize_corner;
bspc config remove_disabled_monitors true;
bspc config merge_overlapping_monitors true;
#bspc config top_padding 23;
#bspc config border_radius 18;
#bspc config bottom_padding 10;
#bspc config left_padding         10
#bspc config right_padding        10
#bspc config click_to_focus       true
#bspc config focus_by_distance    true
#bspc config history_aware_focus  true
#=======================================

#BSPWM coloring
bspc config normal_border_color "#4c566a";
bspc config active_border_color "#1e1e1e";
bspc config focused_border_color "#5e81ac";
bspc config presel_feedback_color "#5e81ac";
#bspc config urgent_border_color "#dd2727";
#=======================================

#Rules
$HOME/.config/bspwm/rules.sh;
#=======================================

#Autostart
$HOME/.config/bspwm/autostart.sh;
