#!/usr/bin/bash
export EDITOR=nvim
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
# fnm
export FNM_BIN="/home/meursault/.local/share/fnm"
export NPM_BIN="/home/meursault/.npm/bin"
export GO_BIN="/opt/go/bin"
export PATH="$FNM_BIN:$NPM_BIN:$GO_BIN:$PATH"

export TERM="xterm-256color"
eval "`fnm env`"

#android
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
