local opt = vim.opt
opt.clipboard="unnamedplus"
opt.guicursor = ""
opt.number = true
opt.relativenumber = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.smartcase = true
opt.wrap = false
opt.swapfile = false
opt.backup = false
opt.undodir = os.getenv("HOME") .. "/.config/.vim-utils/undodir"
opt.undofile = true
opt.hlsearch = true
opt.incsearch = true
opt.termguicolors = true
opt.scrolloff = 8
opt.signcolumn = "yes"
opt.updatetime = 50
opt.ignorecase = true
opt.mouse = 'a'
opt.breakindent = true
opt.splitbelow = true
opt.splitright = true
